name: "AzOps"
description: "-"
author: "Microsoft"
inputs:
  mode:
    description: "AzOps Mode"
    required: true
runs:
  using: "docker"
  image: "docker://jhexpc.azurecr.us/hello-world"
  credentials:
    username: ${{ secrets.ACR_ADMINUSERNAME }}
    password: ${{ secrets.ACR_PASSWORD }}
branding:
  icon: "sunrise"
  color: "green"
