name: Hello World script

on:
  workflow_dispatch:
    # To invoke this action from portal
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
jobs:
  hello-world-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run PowerShell Hello World script
        run: |               
          .\$GITHUB_WORKSPACE\entrypoint.ps1
